[versions]
agp = "8.8.2"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.27"

appcompat = "1.7.0"
constraintlayout = "2.2.1"
coroutinesPlayServices = "1.10.2"
junit = "4.13.2"
androidXJunit = "1.2.1"
espressoCore = "3.6.1"

composeBom = "2025.03.00"

material = "1.12.0"
material3 = "1.3.1"

coreSplashscreen = "1.0.1"

navigation = "2.8.9"
kotlinxSerializationJson = "1.8.0"

lifecycle = "2.8.7"

room = "2.6.1"

datastorePreferences = "1.1.3"

workManager = "2.10.0"

retrofit = "2.9.0"
moshiKotlin = "1.15.1"

playServicesLocation = "21.3.0"

hiltAndroid = "2.51.1"
hiltNavigation = "1.2.0"
hiltWorker = "1.2.0"

desugar = "2.1.5"
calendar = "2.5.0"

aboutLibraries = "11.6.3"

leakcanaryAndroid = "2.14"

[libraries]
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutinesPlayServices" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidXJunit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

# Compose
# https://developer.android.com/develop/ui/compose/setup?hl=ja#setup-compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

# Material
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }

# SplashScreen
# https://developer.android.com/develop/ui/views/launch/splash-screen?hl=ja#getting-started
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

# Navigation
# https://developer.android.com/guide/navigation?hl=ja#set-up
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigation" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Lifecycle
# https://developer.android.com/jetpack/androidx/releases/lifecycle?hl=ja#kotlin
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle" }
androidx-lifecycle-runtime-testing = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "lifecycle" }

# Room(SQLiteデータベース管理)
# https://developer.android.com/jetpack/androidx/releases/room#declaring_dependencies
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

# PreferencesDataStore
# https://developer.android.com/topic/libraries/architecture/datastore?hl=ja#preferences-datastore-dependencies
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }

# WorkerManager(バックグラウンドタスク管理)
# https://developer.android.com/develop/background-work/background-tasks/persistent/getting-started?hl=ja
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workManager" }

# Retrofit(HTTP通信)
# https://square.github.io/retrofit/
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

# FusedLocationProviderClient(位置情報)
# https://developer.android.com/develop/sensors-and-location/location/retrieve-current?hl=ja#setup
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }

# Hilt(依存性注入)
# https://developer.android.com/training/dependency-injection/hilt-android?hl=ja#setup
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }

# HiltNavigation
# https://developer.android.com/training/dependency-injection/hilt-jetpack?hl=ja#viewmodel-navigation
androidx-hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltNavigation" }

# HiltWorker
# https://developer.android.com/training/dependency-injection/hilt-jetpack?hl=ja#workmanager
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWorker" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWorker" }

# kizitonwose/Calendar
# https://github.com/kizitonwose/Calendar
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
kizitonwose-calendar-view = { module = "com.kizitonwose.calendar:view", version.ref = "calendar" }
kizitonwose-calendar-compose = { module = "com.kizitonwose.calendar:compose", version.ref = "calendar" }

# AboutLibraries
# https://github.com/mikepenz/AboutLibraries
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutlibraries-compose-core = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutLibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
aboutlibraries-compose-view = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutLibraries" }

# LeakCanary
# https://square.github.io/leakcanary/getting_started/
# debugImplementation because LeakCanary should only run in debug builds.
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
androidx-room  = { id = "androidx.room", version.ref = "room" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }

